### ISSUE TITLE
`libclang` shared library is not loaded

### ISSUE THREAD

**Issue by bagavi** [twistedfall/opencv-rust#187]
I get the following error : `thread 'main' panicked at 'a 'libclang' shared library is not loaded on this thread', /home/maticd/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-1.0.1/src/lib.rs:1672:1` on building this crate. 

The cargo_metadata has the following `"cargo:rustc-link-search=/usr/lib/x86_64-linux-gnu"` and I get the following on `ls /usr/lib/x86_64-linux-gnu/libclang*` --> `/usr/lib/x86_64-linux-gnu/libclang-10.so    /usr/lib/x86_64-linux-gnu/libclang-9.so.1
/usr/lib/x86_64-linux-gnu/libclang-10.so.1  /usr/lib/x86_64-linux-gnu/libclang-cpp.so.10`

Is it failing because `libclang-9.so` and `libclang-10.so` are present but `libclang.so` is not present? Or does the `clang` crate figure that out?

Complete bash output - https://dpaste.org/GKmS

**Comment by twistedfall** [comment]
Can you try enabling the `clang-runtime` feature for the opencv crate?

**Comment by twistedfall** [comment]
By your reaction I imagine that the problem is fixed, so I'm closing this issue. Please feel free to reopen if that was a misunderstanding!

**Comment by albx79** [comment]
I'm getting the same error with version = "0.81.1", but the `clang-runtime` and `runtime` features have been removed. 

I have clang-16 installed locally; I thought the problem was that I need version 6, but such an old version is almost impossible to install. I kind of managed using nix, but I'm still getting the same error.

Any hints? How are your dev setups? I'm using fedora 38.

Thanks

**Comment by twistedfall** [comment]
Can you please file a new report and attach the `cargo build -vv` log? Please don't try to use older clang, Current clang-16 is tested and supported. The `clang-runtime` feature is removed and this behavior is now the default.

**Comment by albx79** [comment]
done, thanks! 

https://github.com/twistedfall/opencv-rust/issues/462

**Comment by alexisgaziello** [comment]
where can we get available feaures?

**Comment by twistedfall** [comment]
The best source for this list is [`Cargo.toml` file](https://github.com/twistedfall/opencv-rust/blob/master/Cargo.toml#L59)
