### ISSUE TITLE
ToInputArray on `no_array`?

### ISSUE THREAD

**Issue by puckipedia** [twistedfall/opencv-rust#62]
There seems to be no way to use `no_array` as input to `ToInputArray` or `ToOutputArray`? At least, I would presume this should be possible?

**Comment by twistedfall** [comment]
I’ll check, but you can freely replace `no_array` with `Mat::default()`.

**Comment by twistedfall** [comment]
Fixed in v0.26

**Comment by gcstr** [comment]
But how does this even work?
I'm trying to call [find_contours](https://docs.rs/opencv/0.26.1/opencv/imgproc/fn.find_contours.html) that receives `contours: &mut dyn ToOutputArray` as a param but I can't make it work I get the error

```
OpenCV(4.1.2) /tmp/opencv-20191101-13084-e06xvq/opencv-4.1.2/modules/imgproc/src/contours.cpp:1800: error: (-215:Assertion failed) (_contours.kind() == _InputArray::STD_VECTOR_VECTOR || _contours.kind() == _InputArray::STD_VECTOR_MAT || _contours.kind() == _InputArray::STD_VECTOR_UMAT) in function 'findContours'
 (code: -215)
```

**Comment by twistedfall** [comment]
Most of the OpenCV functions don’t allow `no_array()` as output argument. That’s what the error message is telling you: it only accepts `Mat`, `UMat` or `VectorOf...`.

**Comment by gcstr** [comment]
@twistedfall, thanks for taking the time to answer.

I didn't mention in my previous comment that I am using `Mat::default()`, and still getting the error.

```rust
let mut vec = Mat::default().unwrap();
let mut image = imgcodecs::imread("screenshot.png", 0).unwrap();
match imgproc::find_contours(&image, &mut vec, 3, 2, offsetPoint) {
	Ok(T) => {
		println!("ok");
	},
	Err(E) => {
		println!("{}", E);
	}
};
```

**Comment by twistedfall** [comment]
It's more in the "opencv usage" than "opencv-rust crate usage" area, but `findContours` accepts vector of `Mat`|`UMat`|`Vector`, you're passing just `Mat`, so change the first line to:

```rust
    let mut vec = opencv::types::VectorOfMat::new();
```

**Comment by gcstr** [comment]
You're absolutely correct. Not a crate-related issue.
Thanks for the help!
